### ISSUE TITLE
Token RegExp

### ISSUE THREAD

**Issue by sammosna** [Edsol/clickup-vscode-extension#12]
When I import my personal token, I encounter a 'Token Malformed' error. After examining the code [located at this link](https://github.com/Edsol/clickup-vscode-extension/blob/b67f202e423d9fb12a8a6d2ec1a783a4cdd4d854/src/extension.ts#L20C1-L20C50), I noticed that the validation is performed using this regular expression: `/^[a-z]{2}[_]\d{8}[_].{32}/g`, whereas my token is in the format of `pk_12345_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`, which should match the regular expression `/^[a-z]{2}[_]\d{5}[_].{32}/g`

**Comment by Edsol** [comment]
I generalized the regex, I think the second part of the token is an identifier that can be greater or less than 5-8 characters. You can find the change in the newly released version 0.4.
