### ISSUE TITLE
command 'clickup.setToken' not found.

### ISSUE THREAD

**Issue by alexfornuto** [Edsol/clickup-vscode-extension#15]
I've installed the extension and am attempting to register my API token. The README says the command is:

> clickup:setToken: set personal token

Searching for commands finds only "Clickup: Add token". Trying to run that command results in an error:

> **Command 'Clickup: Add token' resulted in an error**
>
>command 'clickup.setToken' not found

**Comment by Edsol** [comment]
fixed on #5f34764

Thank you for making me aware of the issue
