### ISSUE TITLE
List of assigned task.

### ISSUE THREAD

**Issue by HeIIow2** [Edsol/clickup-vscode-extension#17]
Hi, 

First of  all, thanks for the amazing Extension. I would love to see a feature, where the sidebar contains an additional folder, that just lists all tasks assigned to you. 

If this would be implemented the Extension would get Way more useful for me.

Cheers <333

**Comment by Edsol** [comment]
Thank you for the suggestion, it's a feature that I immediately put in and you can already find it in the new release (v. 0.9.0).

Thanks for the support 👍

**Comment by HeIIow2** [comment]
Thank you very much, now this is way better to work with. Another suggestion is sorting it by priority and state. But thank you <333
