### ISSUE TITLE
Add timer for tasks

### ISSUE THREAD

**Issue by M97Chahboun** [Edsol/clickup-vscode-extension#19]
I developed [this extension](https://marketplace.visualstudio.com/items?itemName=vscode-branch-timer.branch-timer) and I can help for add this feature

**Comment by M97Chahboun** [comment]
I will try to start working on it ASAP

**Comment by Edsol** [comment]
I have started a [dedicated branch](/Edsol/clickup-vscode-extension/vscode-branch-timer-extension-merge), I am missing something.

**Comment by Edsol** [comment]
@M97Chahboun added inside v. 1.0.1

**Comment by M97Chahboun** [comment]
@Edsol Im excite to use it, Thanks & I'm sorry for not contribute on it because I'm very busy last month.
