### ISSUE TITLE
Page style improvement

### ISSUE THREAD

**Issue by JasonLamv-t** [Edsol/clickup-vscode-extension#22]
1. Color/Theme follow the vscode setting. Now it is a white background even in dark mode.
2. Better typography and design. Now is's too simple.

You do a really good job. :+1: I am interested in this project, but I'm new to vscode extension development. If you want help plz reach out te me.

**Comment by Edsol** [comment]
thanks for the feedback and suggestions, hope to correct as soon as possible. If you would like to contribute to the extension that would be great

**Comment by Edsol** [comment]
I have refactored the entire UI, it now supports changing themes and everything is graphically more accurate and detailed
