### ISSUE TITLE
Lists and Folders don't Show When on Same Level

### ISSUE THREAD

**Issue by chsegala** [Edsol/clickup-vscode-extension#25]
My project has a space with multiple lists under the space and a single folder, the folder shows but all the lists under the space directly are missing.

```
Space
-- Folder 1   <- shows fine
  -- List 3   <- shows fine
  -- List 4   <- shows fine
-- List 1     <- missing
-- List 2     <- missing
```

**Comment by Edsol** [comment]
I have reproduced the tree as you indicated but do not encounter any problems

![image](https://github.com/user-attachments/assets/1c19ad98-5ff2-4d42-88e7-3d3b42e6c19f)

Are you sure you have the latest version?

**Comment by chsegala** [comment]
Freshly installed
![image](https://github.com/user-attachments/assets/a279bca9-22d6-40a5-b6b3-01e645165707)

This is the clickup space:
![image](https://github.com/user-attachments/assets/be5f0c51-bf47-45fb-97d8-c82366048284)

This is the extension:
![image](https://github.com/user-attachments/assets/92237246-118f-422b-9e46-9e677fc44efd)

I'm very new to click-up, I'm not really aware of what could be causing this

**Comment by Edsol** [comment]
can you keep at least the first letter clear? so we can identify the same elements in the two images. Could you have given restrictions to the space where you don't display all the lists?

**Comment by chsegala** [comment]
I color coded them also.
On Extension: Everything gray is what's inside the "salmon" (F) folder.
On Clickup: Everything black is what should be sibling of "salmon" (F), but they don't show, children of "purple" (E).

![image](https://github.com/user-attachments/assets/4217d77d-e43a-47d9-924b-9bc777a0e6d4)
![image](https://github.com/user-attachments/assets/446470d4-eadb-4006-a9d5-bcab57f0bcc2)

**Comment by Edsol** [comment]
now the entries are clearer, the case is the same as the one I showed before and I should have no problems with the display. on the element starting with E (space) I see a padlock, which indicates that there are restrictions and customizations on that space, are there multiple users using that space? because it is the only case I have not tested since my test instance has only one user.

**Comment by chsegala** [comment]
Yes, that space is locked to a certain group of people.
Christian Segala

**Comment by Edsol** [comment]
I don't detect any problems, unfortunately I can't reproduce the problem without more information. If you are not the owner of the offending space it is probably a permissions issue.

Update to the latest version (1.2.0), I added debug mode in the extension settings, this may help detect the problem (look at the vscode console log)

**Comment by chsegala** [comment]
The only thing I see related on the logs is:
```
2024-11-04 11:07:07.971 [warning] [clickup]: Couldn't find message for key addFolder.title.
2024-11-04 11:07:07.971 [warning] [clickup]: Couldn't find message for key deleteFolder.title.
```

This happens multiple times and keeps happening from time to time

**Comment by Edsol** [comment]
aggiorna l'estensione, abilita la modalità debug, chiudi e ripari vscode
<img width="1100" alt="SCR-20241104-nlqh" src="https://github.com/user-attachments/assets/a77b1319-4a6c-48fa-b711-8809c81ee2a5">

**Comment by chsegala** [comment]
The only "tab" there's clickup related output is the "shared".

![image](https://github.com/user-attachments/assets/ee6c8830-f960-4cb4-8a1d-62a268adaa39)

**Comment by Edsol** [comment]
I'm on macos, the menu changes based on your operating system
![image](https://github.com/user-attachments/assets/a4877a04-2809-4983-aa17-d7b8acab06e4)

**Comment by chsegala** [comment]
Here is the console info (I didn't know of this console debug, sorry).

Something that caught my attention is the `members` property, it does not list the teams. My permission is through the team.

```
// spaces
{
    "projectId": "45XXXX46",
    "result": [
        {
            "id": "66XXXX74",
            "name": "E Purple",
            "color": "#7b68ee",
            "private": true,
            "avatar": null,
            "admin_can_manage": true,
            "statuses": [ /* redacted */ ],
            "multiple_assignees": true,
            "features": { /* redacted */ },
            "archived": false,
            "members": [ /* shows 2 people, none of them is me, though it does not show the team (which I'm in) */ ]
        }
        /* other spaces here */
    ]
}

// folders of E Purple
{
    "space": { /* same as above E Purple */},
    "result": [
        {
            "id": "90XXXXX89",
            "name": "F Salmon",
            "orderindex": 13,
            "override_statuses": true,
            "hidden": false,
            "space": {
                "id": "66XXXX74",
                "name": "E Purple"
            },
            "task_count": "88",
            "archived": false,
            "statuses": [ /* redacted */ ],
            "lists": [ /* Successful List Here */ ],
            "permission_level": "create"
        }
    ]
}

// folder less list of E Purple
{
    "space": { /* same as above E Purple */},
    "result": []
}
```

**Comment by Edsol** [comment]
the `folder less list` is empty, this rules out an extension malfunction. 
I don't think there is a problem with the extension. Try making the call through [https://clickup.com/api/clickupreference/operation/GetFolderlessLists/](API) .
Does it return the correct list?

**Comment by chsegala** [comment]
I guess it won't work...
```
{
  "err": "Oauth token not found",
  "ECODE": "OAUTH_019"
}
```

Probably it won't work on API Token, that could be it.

**Comment by Edsol** [comment]
you must use the personal token, the same one you entered of the vscode extension the first time.

**Comment by chsegala** [comment]
yep, empty list

**Comment by chsegala** [comment]
Since this seems to be an edge case and something related to my org configuration, I'm gonna close this as a non-issue.
