### ISSUE TITLE
Multiple Start timer buttons in Status Bar

### ISSUE THREAD

**Issue by ch4r-ch4r** [Edsol/clickup-vscode-extension#28]
Setup:
* `Track Task Time` disabled in Extension Settings.
* IDE: Cursor Version 0.42.4 (VSCode Version 1.93.1)

There are multiple "Start timer" unresponsive button in the Status Bar.

![0PYnDQeZ@2x](https://github.com/user-attachments/assets/76c14318-1478-4121-83bb-02806bcdeefd)

**Comment by Edsol** [comment]
fixed in v1.3.1
