### ISSUE TITLE
Folders are not showing

### ISSUE THREAD

**Issue by gavinharris-dev** [Edsol/clickup-vscode-extension#4]
Cannot see lists that exist within Folders.

On our ClickUp Project (Space) we are using Folders to logically group our Lists, I've just installed this application but can only find the Top Level lists; the ones residing within the Folders are not visible.

Reference: https://docs.clickup.com/en/articles/1045623-hierarchy-structure-in-clickup

**Comment by Edsol** [comment]
@gavinharris-dev I fixed with last release (0.1.0), let me know if you still have problems

**Comment by gavinharris-dev** [comment]
Amazing! Just updated the plugin and yep, there are the folders! Thank you!

**Comment by Edsol** [comment]
it is good to hear that it is now working correctly, if you encounter any other problems I am available :+1:
