### ISSUE TITLE
Tasks in some lists not showing

### ISSUE THREAD

**Issue by reeceatkinson** [Edsol/clickup-vscode-extension#5]
In some lists they show tasks. But on others they don't show any when I have quite a few in them
<img width="226" alt="image" src="https://user-images.githubusercontent.com/78908925/176725108-02d83583-7451-45f5-ac1c-4d4bcb5353b5.png">

**Comment by ILoomans** [comment]
Interesting, From what i gather from my own look at this is it happens in the child folders where there is a list at the same level of the parent folders (don't know if that made sense)

Lets say this is the structure

Folder1
Folder2
List1

I am able to see the tasks in List1. But the lists in Folder1 And Folder2 are empty. 

Im looking for a solution to this!

**Comment by Edsol** [comment]
Thanks for the tip, fixed in 0.1.2 release

![image](https://user-images.githubusercontent.com/19670024/176923050-d1b5f2bd-025f-4fc2-a4a8-5164b6858dab.png)

**Comment by reeceatkinson** [comment]
Thanks!
